### ISSUE TITLE
Not blocking applet after entering some number of incorrect PINs.

### ISSUE THREAD

**Issue by stepgenn** [St4lkerino/PV204_PROJEKT#15]
**Problem identification:**  Not blocking applet after entering some number of incorrect PINs
**Severity:** high
**Description:** During one session, the maximal number of tries of entering a PIN is limited. But the number of tries left is not stored in a persistent array in EEPROM and by starting a new session, it is set back to the original value (3). Therefore, there is not a limited number of attempts to connect to the card as well as a number of entering incorrect PIN. Since the correctness of entered PIN can be easily checked (messages 63C2, 62C1, 63C0), one can easily find the correct PIN by brute force attack. 
**Remediation:** The applet should be blocked after entering some number of incorrect PINs.

**Comment by sobuch** [comment]
Are you sure you started a new session each time and didnt rather initialize a new card? This functionality is already implemented and tested

**Comment by stepgenn** [comment]
Yes, I just had one instance of SecureCardChannel and called multiple times your method initSession().

**Comment by St4lkerino** [comment]
I remember this. Basically every connect call from the card manager inside initSession() installs the applet again. Therefore builds the class, which resets the counter. This should theoretically not be an issue on a real card, where the applet would only be installed once.

**Comment by stepgenn** [comment]
Yes, sorry, you are right. I got confused by the method name.
